const mongoose = require("mongoose");

const illSchema = new mongoose.Schema({
  reqId: { type: Number },
  quoteType: { type: String },
  locationDetails: [{ type: Object }],
  contactDetailsForAll: { type: Object },
  companyId: { type: String },
  createdDate: { type: Date, default: Date.now },
  createdBy: { type: String },
  status: { type: String, default: "DRAFT" },
  cxmCommonStatus: { type: String, default: "DRAFT" },
  quoteStatus: { type: String, default: "NOTCOMPLETED" },
  isActive: { type: Boolean, default: true },
  isBulkUpload: { type: Boolean, default: false },
  ebsAccountNo: { type: String },
  parentRole: { type: String },
  partyId: { type: String },
  partyNo: { type: String },
  panNo: { type: String },
  totalARC: { type: Number },
  totalOTC: { type: Number },
  totalPrice: { type: Number },
  companyName: { type: String },
  customerNumber: { type: String },
  customermail: { type: String },
  customerName: { type: String },
  mailIdList: [{ type: Object }],
  pageTracker: { type: String },
  // sameBillToForAll: { type: Boolean },
  isPoNo: { type: Boolean, default: true },
  poRefNo: { type: String },
  poDate: { type: String },
  poDateISO: { type: String },
  poUpload: { type: Boolean, default: false },
  poUploadFileName: { type: String },
  hasRateCard: { type: Boolean, default: false },
  iscxmFiberApproval: { type: Boolean, default: false },
  iscxmWirelessApproval: { type: Boolean, default: false },
  rateCode: { type: String },
  orderId: { type: String, default: "" },
  orderDate: { type: String },
  opportunityId: { type: String },
  bookingNo: { type: String },
  soNumber: { type: String },
  soNumberUpdateDate: { type: String },
  bookingNoUpdateDate: { type: String },
  irDate: { type: String },
  orderImplementedDate: { type: Date, },
  orderProvisingDate: { type: Date, },
  irUpdatedDate: { type: String },
  linkId: { type: String },
  orderRefNo: { type: Number, default: null },
  cxmConformation: { type: Boolean },
  isOpportunitySent: { type: Boolean, default: false },
});

module.exports = illSchema;
// module.exports = mongoose.model("quoteills", illSchema);
